# BANCO ORACLE (PROD)
spring.datasource.url=
spring.datasource.username=RM
spring.datasource.password=1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY
spring.flyway.url=
spring.flyway.user=RM
spring.flyway.password=1
spring.flyway.locations=classpath:db/migration