# BANCO H2 (DEV)
spring.datasource.url=jdbc:h2:mem:specradar;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Ford
spring.datasource.password=Fiap2026

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# FLYWAY
spring.flyway.url=jdbc:h2:mem:specradar;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=VALUE
spring.flyway.user=Ford
spring.flyway.password=Fiap2026
spring.flyway.locations=classpath:db/migration

# SSL desabilitado em dev - HTTP local
server.ssl.enabled=false