CREATE TABLE ford_usuarios (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(100)  NOT NULL,
    email     VARCHAR2(150)  NOT NULL,
    senha     VARCHAR2(255)  NOT NULL,
    role      VARCHAR2(20)   NOT NULL,
    ativo     NUMBER(1)      DEFAULT 1 NOT NULL,
    criado_em TIMESTAMP      NOT NULL,

    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT chk_usuarios_role CHECK (role IN ('ADMIN', 'ANALISTA'))
);