CREATE TABLE ford_veiculos (
    id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca     VARCHAR2(30)   NOT NULL,
    modelo    VARCHAR2(100)  NOT NULL,
    versao    VARCHAR2(100)  NOT NULL,
    ano       NUMBER(4)      NOT NULL,
    ativo     NUMBER(1)      DEFAULT 1 NOT NULL,
    criado_em TIMESTAMP      NOT NULL,

    CONSTRAINT chk_veiculos_marca CHECK (marca IN (
        'TOYOTA', 'VOLKSWAGEN', 'CHEVROLET', 'FIAT',
        'HYUNDAI', 'NISSAN', 'MITSUBISHI', 'JEEP',
        'RAM', 'MERCEDES'
    ))
);