CREATE TABLE ford_especificacoes (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id NUMBER         NOT NULL,
    atributo   VARCHAR2(100)  NOT NULL,
    valor      VARCHAR2(255)  NOT NULL,
    unidade    VARCHAR2(50),
    disponivel NUMBER(1)      DEFAULT 1 NOT NULL,
    criado_em  TIMESTAMP      NOT NULL,

    CONSTRAINT fk_especificacoes_veiculo
        FOREIGN KEY (veiculo_id)
        REFERENCES ford_veiculos(id)
);