CREATE TABLE ford_consultas (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id   NUMBER    NOT NULL,
    veiculo_id   NUMBER    NOT NULL,
    realizada_em TIMESTAMP NOT NULL,

    CONSTRAINT fk_consultas_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES ford_usuarios(id),

    CONSTRAINT fk_consultas_veiculo
        FOREIGN KEY (veiculo_id)
        REFERENCES ford_veiculos(id)
);